# 定时向所有在线玩家发送消息
broadcast-msg:
  # 功能开关
  enable: false
  # 两次消息之间的时间间隔，单位为秒
  interval: 60
  # 待发送的消息，按顺序依次发送
  messages:
    - "<gray>» 加入QQ群聊</gray><color:#eccc68><hover:show_text:'点击复制'><click:copy_to_clipboard:830277457>830277457</click></hover></color><gray>获取最新消息</gray>"

# 虚假种子信息
fake-seed:
  # 功能开关
  enable: false
  # 假种子生成类型, 都不符合则返回真种子
  # FIXED: 固定种子类型，需要手动输入
  # RANDOM: 随机种子类型，仅在插件加载配置文件时会生成
  fake-type: FIXED
  # 虚假的种子码
  seed: "2023080402333333"
  # 返回真种子码需要的权限
  unlock-real-perms: "lightutils.realseed"
  # 随机生成的种子码长度
  # 具体长度=1+设置的值
  length: 15

# 修改插件列表显示
modify-plugins:
  # 功能开关
  enable: false
  # 需要隐藏的插件的名称, 以插件列表的为标准
  hides: []
  # 执行显示插件需要的权限
  execute-perms: "lightutils.plugins"
  # 获取真实的插件列表需要的权限
  unlock-real-perms: "lightutils.realplugins"

# 自由视角(观察者)，切换时返回原来位置
freecam:
  # 是否启用
  enable: false
  # 移动距离限制，若半径范围内无玩家(包括切换前玩家自己的位置)
  # 则关闭freecam
  limit: 200
  # 需要的权限
  execute-perms: "lightutils.freecam"

# 飞行功能
fly:
  # 功能开关
  enable: false
  # 所需权限，留空或""为不需
  execute-perms: "lightutils.fly"

utils:
  # 取代原版 setworldspawn 命令
  # 强制使用坐标参数, 不考虑位置安全性
  setworldspawn:
    # 功能开关
    enable: false
    # 坐标 x,y,z (double)
    location: "world,0,100,0"
  cancels:
    player-join-leave-msg: true
    entity-farmland-revert: true
